FROM jenkins/inbound-agent:latest

USER root

# Install base dependencies (minimal & secure)
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unzip \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install Terraform (HTTPS enforced)
RUN curl --fail --location --silent --show-error \
         --proto '=https' --tlsv1.2 \
         https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip \
         -o terraform.zip \
    && unzip terraform.zip \
    && mv terraform /usr/local/bin/terraform \
    && rm terraform.zip

# Install Sonar Scanner (HTTPS enforced)
RUN curl --fail --location --silent --show-error \
         --proto '=https' --tlsv1.2 \
         https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip \
         -o sonar.zip \
    && unzip sonar.zip \
    && mv sonar-scanner-* /opt/sonar-scanner \
    && ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner \
    && rm sonar.zip

USER jenkins